# in _config.yml
title: "Robotic Building Lab Guides"
logo: images/logo.png
execute:
  execute_notebooks: "off"

only_build_toc_files: true

exclude_patterns: [LICENSE.md, .blog/ images/**.*,./**/*.py, ./**/*.jpg ]

# Information about where the book exists on the web
repository:
  url  : https://github.com/Robotic-Building-TU-Delft/dcc-collab.git

html:
  use_repository_button: true
  comments:
    utterances:
      repo: "Robotic-Building-TU-Delft/dcc-collab.git" 
  
  home_page_in_navbar: false# in _config.yml
